### PR TITLE
Autodetect OS in "make" script 

### PR DESCRIPTION
**Pull request by clairekope**
Previously the "make" script had to be edited by hand depending on whether you were building it for Mac OS or Linux. This small PR adds logic to adapt to these two operating systems. The Linux commands assume you are building on a system where FlexiBLAS is available to be your LAPACK library, such as MSU's HPCC.

### CODE REVIEW

**Review by sara-amano — CHANGES_REQUESTED** [review]
Could we store the output of uname in a variable, e.g. 
`myos=$(uname)`
and use that for the logicals? 
Maybe `expr` complicates this, I am not sure why it's needed. 

Would it be more sensible to rename "make" to "compile.sh"? 

Since we removing `ar rcs libLinAlg.a LinAlg.o`, we can remove `-L .` from line 61. 

This breaks if we have another BLAS library, such as openblas rather than flexiblas. Is there a way to incorporate this into this script, or are we entering into make/cmake territory. 
One hacky way is to use: 
`gfortran -l openblas |& grep -q "cannot find"; echo $?`
returns 1, but 
`gfortran -l openblass |& grep -q "cannot find"; echo $?`
returns 0.

**Comment by clairekope** [comment]
> Could we store the output of uname in a variable, e.g. `myos=$(uname)` and use that for the logicals? Maybe `expr` complicates this, I am not sure why it's needed.

Storing this as a variable is a much cleaner approach; I'll make that change. I'm not the most proficient bash coder, so I pulled the OS detection snippet from StackOverflow. In trying to find the original article however, I've found cleaner approaches.

> Would it be more sensible to rename "make" to "compile.sh"?

We could certainly make that change! I just didn't want to go changing directory structure too much.

> Since we removing `ar rcs libLinAlg.a LinAlg.o`, we can remove `-L .` from line 61.

Good catch, thanks.

> This breaks if we have another BLAS library, such as openblas rather than flexiblas. Is there a way to incorporate this into this script, or are we entering into make/cmake territory. One hacky way is to use: `gfortran -l openblas |& grep -q "cannot find"; echo $?` returns 1, but `gfortran -l openblass |& grep -q "cannot find"; echo $?` returns 0.

I can easily switch it back to openblas; it's the default BLAS library used by flexiblas anyway.

**Comment by clairekope** [comment]
@sara-amano I've made the requested changes and also added the option to compile uegCCD in debug mode by running `./compile.sh -d`. Please test on a Mac to make sure the more streamlined OS detection still works as expected :)

I do feel that renaming the script to `compile.sh` reduces confusion since it is just a bash script and not a Makefile. Alternatively, we could also call it `make.sh`. We can also maybe see what @jamesjshepherd thinks about this? I don't have strong feelings either way and can easily change it back.

**Comment by clairekope** [comment]
James doesn't particularly care what it's called, I  have a slight preference for `make.sh` because of conventions among user-compiled software so I went with that.

**Comment by william-vanbenschoten** [comment]
I added myself to the reviewer list (and am including this comment) so it is clear I was providing input for the PR review by Sara.

**Review by sara-amano — APPROVED** [review]
This all looks good to me. We tried it on my Mac (and Will's) as well as Linux and it worked, with and without the -d. 

At some point, it would be nice to have some sort of config files that this would reference, as we had to manually load OpenBlas on Linux. But that is beyond the scope of these changes.

**Review by william-vanbenschoten — APPROVED** [review]
This looks good to me!

**Pull request merged**
